-- Active: 1751256646599@@127.0.0.1@3306
-- 创建数据库
CREATE DATABASE IF NOT EXISTS mall DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mall;

-- 管理后台用户表
CREATE TABLE IF NOT EXISTS admin_user (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password VARCHAR(32) NOT NULL COMMENT '密码（MD5密文）',
  nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像',
  status TINYINT DEFAULT 1 COMMENT '状态（1启用 0禁用）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='管理后台用户表';

-- 插入admin用户（密码admin的MD5密文：21232f297a57a5a743894a0e4a801fc3）
INSERT INTO admin_user (username, password, nickname, status) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3', '管理员', 1);

-- 用户表
CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  openid VARCHAR(64) NOT NULL UNIQUE COMMENT '微信openid',
  nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像',
  gender TINYINT DEFAULT 0 COMMENT '性别（0未知 1男 2女）',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  status TINYINT DEFAULT 1 COMMENT '状态（1正常 0禁用）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='小程序用户表';

-- 商品分类表
CREATE TABLE IF NOT EXISTS category (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  name VARCHAR(50) NOT NULL COMMENT '分类名称',
  image VARCHAR(255) DEFAULT NULL COMMENT '分类图片',
  sort INT DEFAULT 0 COMMENT '排序',
  status TINYINT DEFAULT 1 COMMENT '状态（1启用 0禁用）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='商品分类表';

-- 商品表
CREATE TABLE IF NOT EXISTS goods (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  category_id INT NOT NULL COMMENT '所属分类ID',
  name VARCHAR(100) NOT NULL COMMENT '商品名称',
  image VARCHAR(255) DEFAULT NULL COMMENT '商品主图',
  price DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  stock INT DEFAULT 0 COMMENT '库存',
  status TINYINT DEFAULT 1 COMMENT '上架状态（1上架 0下架）',
  description TEXT COMMENT '商品描述',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (category_id) REFERENCES category(id)
) COMMENT='商品表';

-- 轮播图表
CREATE TABLE IF NOT EXISTS banner (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  image VARCHAR(255) NOT NULL COMMENT '轮播图片',
  title VARCHAR(100) DEFAULT NULL COMMENT '标题',
  link VARCHAR(255) DEFAULT NULL COMMENT '跳转链接',
  sort INT DEFAULT 0 COMMENT '排序',
  status TINYINT DEFAULT 1 COMMENT '状态（1启用 0禁用）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='轮播图表';

-- 购物车表
CREATE TABLE IF NOT EXISTS cart (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  user_id INT NOT NULL COMMENT '用户ID',
  goods_id INT NOT NULL COMMENT '商品ID',
  quantity INT DEFAULT 1 COMMENT '商品数量',
  checked TINYINT DEFAULT 1 COMMENT '是否选中（1选中 0未选中）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (goods_id) REFERENCES goods(id)
) COMMENT='购物车表';

-- 收货地址表
CREATE TABLE IF NOT EXISTS address (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  user_id INT NOT NULL COMMENT '用户ID',
  receiver VARCHAR(50) NOT NULL COMMENT '收货人',
  phone VARCHAR(20) NOT NULL COMMENT '联系电话',
  province VARCHAR(50) NOT NULL COMMENT '省',
  city VARCHAR(50) NOT NULL COMMENT '市',
  district VARCHAR(50) NOT NULL COMMENT '区',
  detail VARCHAR(255) NOT NULL COMMENT '详细地址',
  is_default TINYINT DEFAULT 0 COMMENT '是否默认地址（1是 0否）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (user_id) REFERENCES user(id)
) COMMENT='收货地址表';

-- 订单表
CREATE TABLE IF NOT EXISTS `order` (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  order_no VARCHAR(32) NOT NULL UNIQUE COMMENT '订单号',
  user_id INT NOT NULL COMMENT '用户ID',
  status TINYINT DEFAULT 0 COMMENT '订单状态（0待支付 1已支付 2已发货 3已完成 4已取消）',
  pay_status TINYINT DEFAULT 0 COMMENT '支付状态（0未支付 1已支付）',
  total_amount DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  address_id INT NOT NULL COMMENT '收货地址ID',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (address_id) REFERENCES address(id)
) COMMENT='订单表';

-- 订单商品表
CREATE TABLE IF NOT EXISTS order_goods (
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  order_id INT NOT NULL COMMENT '订单ID',
  goods_id INT NOT NULL COMMENT '商品ID',
  goods_name VARCHAR(100) NOT NULL COMMENT '商品名称',
  goods_image VARCHAR(255) DEFAULT NULL COMMENT '商品图片',
  goods_price DECIMAL(10,2) NOT NULL COMMENT '商品单价',
  quantity INT DEFAULT 1 COMMENT '购买数量',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  FOREIGN KEY (order_id) REFERENCES `order`(id),
  FOREIGN KEY (goods_id) REFERENCES goods(id)
) COMMENT='订单商品表'; 